name: e2e-tests-on-schedule-trigger
on:
  schedule:
    - cron: '5 16 * * *' # This will run the workflow every day at 4:05 PM UTC, which is 9:35 PM IST

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
